### ISSUE TITLE
Actor subscribed to multiple observables

### ISSUE THREAD

**Issue by bicepjai** [biaslab/Rocket.jl#13]
Is it possible for actor to receive multiple messages from multiple subjects ?

**Comment by bauglir** [comment]
Yes, you're probably looking for [`merged`](https://biaslab.github.io/Rocket.jl/stable/observables/types/merged/#observable_merged). This will allow you to create a new observable which receives messages from multiple other observables, which you then subscribe to using your actor.

I guess you might be thinking more along the lines of subscribing multiple times with an actor to different subjects. That is generally not something you do in these types of frameworks (if it's at all possible).

**Comment by bicepjai** [comment]
Thanks for your suggestion. I was looking for [Zipped Observable](https://biaslab.github.io/Rocket.jl/stable/observables/types/zipped/) where i can have multiple sources enter an actor in sync

**Comment by bauglir** [comment]
I'm not intimately familiar with the implementation details of the zipped observable in Rocket. That being said, in general, the way the 'zip' operator works is that it waits to emit its n-th element until the n-th emission from all of its source observables is available.

So, say you have two observables one of which emits every second and the other every two seconds. What will happen if you zip these is that the zipped observable will emit the first emission from both the first and second observable after two seconds, then the second of both after 4 seconds, etc. To see this in action (using Rx.js) you can go to https://rxviz.com/examples/custom and paste the following code:
```
const { merge, interval } = Rx;
const { zip } = RxOperators;

const fast = interval(1000);
const slow = interval(2000);
const zipped = fast.pipe(zip(slow));

merge(foo, bar, zipped);
// You'll see one emission of 0 after 1 second from `fast`, then three emissions after 2 seconds (1 from
// `fast`, 0 from `slow` and 0,0 from `zipped`), then one emission of 2 after 3 seconds from `fast`, then
// three emissions after 4 seconds (3 from `fast`, 1 from `slow` and `1, 1` from `zipped`), etc.
```

What happens in the case where there is a large discrepancy between the arrival of emissions largely depends on the size of the internal buffer used to track emissions from the source observables.

Other constructors/operators that may be of interest are [`combineLatest`](https://biaslab.github.io/Rocket.jl/stable/observables/types/combined/#Rocket.combineLatest) which creates an observable which emits the combination of all the most recent emissions from its sources whenever any of them emits a new value and [`with_latest`](https://biaslab.github.io/Rocket.jl/stable/operators/join/with_latest/#Rocket.with_latest) which has similar behavior, but only emits the latest emission from all the sources when the 'primary' (i.e. the first) source emits a new value.
