### ISSUE TITLE
unsubscribing from asynchronous observables

### ISSUE THREAD

**Issue by gasagna** [biaslab/Rocket.jl#14]
Apologies for the long MWE. Not sure it is really an issue, but I have not been able to figure this out from the available documentation.

I am developing an agent that subscribes to an unbounded stream of (network) asynchronous events and can be controlled through keyboard presses. My logic to end the execution of the agent and close the program is that upon pressing `c`, the agent unsubscribes from all observables and should quit. Except that it really doesn't at the moment. See MWE below. 

Am I misusing the SyncActor logic?

```julia
using Rocket

# get single char from keyboard, excluding return
# https://stackoverflow.com/questions/56888266/how-to-read-keyboard-inputs-at-every-keystroke-in-julia/56893331#56893331
function getchar()
    ret = ccall(:jl_tty_set_mode, Int32, (Ptr{Cvoid},Int32), stdin.handle, true)
    ret == 0 || error("unable to switch to raw mode")
    c = read(stdin, Char)
    ccall(:jl_tty_set_mode, Int32, (Ptr{Cvoid}, Int32), stdin.handle, false)
    return c
end

# a basic logger controllable by keyboard presses
mutable struct Agent <: Actor{Union{Char, Int}} 
    subs :: Vector{Any}
    Agent() = new(Any[])
end

Rocket.on_next!(a::Agent, c::Int) = println("got Int  ", c)

function Rocket.on_next!(a::Agent, c::Char)
    println("got Char ", c )
    # close on pressing c
    if c == 'c'
        foreach(unsubscribe!, a.subs)
        println("done") # hangs after this
    end
end

Rocket.on_complete!(a::Agent) = println("completed")

# int sources
intsource = make(Int) do actor
    i = 0
    while true
        next!(actor, i)
        i+=1
        sleep(1)
    end
end

# keyboard events
keysource = make(Char) do actor
    while true
        next!(actor, getchar())
    end
end

# create sync agent
agent = sync(Agent())

# subscribe to asynchronous event streams
sub1 = subscribe!(intsource |> safe() |> async(), agent)
sub2 = subscribe!(keysource |> safe() |> async(), agent)

# store subscriptions
push!(agent.actor.subs, sub1)
push!(agent.actor.subs, sub2)

yield()
wait(agent)
```

**Comment by bvdmitri** [comment]
Hi @gasagna ,

Thanks for your feedback! I tried your example and indeed it hangs, but the reason for this is simple. `wait(agent)` waits for an agent to receive a completion event with `complete!(agent)`. If you do, e.g.:

```julia
function hang_test()
  # create sync agent
  agent = sync(Agent())
  
  # subscribe to asynchronous event streams
  sub1 = subscribe!(intsource |> safe() |> async(), agent)
  sub2 = subscribe!(keysource |> safe() |> async(), agent)
  
  # store subscriptions
  push!(agent.actor.subs, sub1)
  push!(agent.actor.subs, sub2)
  
  @async begin
      sleep(5) # I assume here that within 5 seconds I will press 'c'
      println("Complete sync")
      complete!(agent) # After this line is executed `wait` will return 
  end
  
  yield()
  wait(agent)
end
```
This is an iffy solution of course, but just as a note if you use `sync` and `wait` you need to find a way to send a completion event to your agent (not the original one, but the agent returned from `sync(something)` function). It is also better to use functions inside REPL with async/sync code execution.

I'm not sure about your application logic, but it is not necessary to use `sync` and `wait` at all. They exist mostly for testing purposes, in real application it is better to write everything in a non-blocking way, e.g. this function also works

```julia
function nosync_test()
    @async begin
        agent = Agent()

        # subscribe to asynchronous event streams
        sub1 = subscribe!(intsource |> safe() |> async(), agent)
        sub2 = subscribe!(keysource |> safe() |> async(), agent)

        # store subscriptions
        push!(agent.subs, sub1)
        push!(agent.subs, sub2)

        yield()
    end
end
```

P.S. BTW while looking into your example I think I found another bug in sync actor implementation, but it should be unrelated to your example.

**Comment by bvdmitri** [comment]
Ah, sorry for being unclear. I didn't mean you should use REPL, I personally have never used REPL for development. I meant **if** you use REPL it is better to use functions with async code in it. But it is of course better to have a self contained program.

Your approach with controller should be fine, but it violates the rule that you should never send anything after you've sent a completion event, so simple else statement for `next!` should help here. While in principle there is nothing wrong in sending something after completion event happened it may cause some hard to find bugs, because not all of the operators check it and some of them rely on this rule.

Feel free to close this issue if it helped you with your question.

**Comment by gasagna** [comment]
Hi @bvdmitri,

thanks for the info. It's easy to add a `break` statement after `complete!`. 

Thanks for the help!
