### ISSUE TITLE
buffering asynchronous events closer in time than given `delay`

### ISSUE THREAD

**Issue by gasagna** [biaslab/Rocket.jl#15]
Hi, 

I am trying to implement a custom operator that lumps together in a `Vector` items from an asynchronous observable that are closer than a specified `delay` and releases the buffer as a vector once `delay` has passed since the last item was received.  In addition, the buffer is also released if its length exceeds `maxsize`.

This is an attempt to model what described [here](https://gist.github.com/staltz/868e7e9bc2a7b8c1f754) and specifically the first operation of this marble [diagram](https://camo.githubusercontent.com/c1a315799c0b2d29520cf943dfeb4df306d38bdb1331cf512b26e7d2c78a801b/687474703a2f2f692e696d6775722e636f6d2f484d47574e4f352e706e67) (from the first link). 

As far as I understand from the available library in this package, this functionality is not yet available. 

This is my current attempt, and I would welcome any help. If this (and future ones too) material is better suited for the discourse forum, please close the issue.

```julia
import Rocket
import Dates

struct ThrottleBufferOperator <: Rocket.InferableOperator 
      delay :: Int # delay in millisecond
    maxsize :: Int # maximum buf size
end

throttlebuffer(delay::Int, maxsize::Int) = ThrottleBufferOperator(delay, maxsize)

Rocket.on_call!(::Type{T}, ::Type{Vector{T}}, op::ThrottleBufferOperator, source) where {T} =
    Rocket.proxy(Vector{T}, source, ThrottleBufferProxy(op.delay, op.maxsize))

Rocket.operator_right(operator::ThrottleBufferOperator, ::Type{T}) where T = Vector{T}

struct ThrottleBufferProxy <: Rocket.ActorProxy 
      delay :: Int # delay in millisecond
    maxsize :: Int # maximum buf size
end

Rocket.actor_proxy!(::Type{Vector{T}}, op::ThrottleBufferProxy, actor) where {T} =
    ThrottleBufferActor{T}(actor, op.delay, op.maxsize)

mutable struct ThrottleBufferActor{T, A} <: Rocket.Actor{T}
         actor :: A
          data :: Vector{T}
    lastupdate :: Dates.DateTime
     completed :: Condition
    function ThrottleBufferActor{T}(actor::A, delay::Int, maxsize::Int) where {T, A}

        buf = new{T, A}(actor, T[], Dates.now(), Condition())
       
        @async while true
            # do next! if last update was more then `delay` milliseconds ago
            if length(buf.data) > 0
                if Dates.now() - buf.lastupdate > Dates.Millisecond(delay)
                    __next!(buf)
                end
            end

            # clear buffer if needed
            if length(buf.data) == maxsize
                __next!(buf)
            end

            # granularity
            sleep(0.001)
        end
        
        return buf
    end
end

function __next!(buf::ThrottleBufferActor)
    Rocket.next!(buf.actor, copy(buf.data)) # release copy of buffer
    resize!(buf.data, 0)  # reset buffer
    notify(buf.completed) # necessary for correct completeion
end

function Rocket.on_next!(buf::ThrottleBufferActor{T, A}, item::T) where {T, A}
    push!(buf.data, item)
    buf.lastupdate = Dates.now()
    return nothing
end

Rocket.on_error!(buf::ThrottleBufferActor, err) = Rocket.error!(buf.actor, err)

Rocket.on_complete!(buf::ThrottleBufferActor) = 
    (wait(buf.completed); Rocket.complete!(buf.actor))


source = Rocket.make(Int) do actor
    # will print [0, 1, 2]
    Rocket.next!(actor, 0)
    Rocket.next!(actor, 1)
    Rocket.next!(actor, 2)
    sleep(500/1000)
    
    # will print [3, 4]
    Rocket.next!(actor, 3)
    sleep(10/1000)
    Rocket.next!(actor, 4)
    sleep(1000/1000)

    # will print [5]
    Rocket.next!(actor, 5)

    # will complete after [5] was printed
    Rocket.complete!(actor)
end

Rocket.subscribe!(source |> Rocket.async() |> throttlebuffer(100, 10), Rocket.logger())
```

However, I am not happy with the way the `@async` task in the constructor of `ThrottleBufferActor` is polling at high frequency. I suspect that there is a different mechanisms using Julia's task programming that would be better.

I also worry about possible race conditions, and potentially loosing some items due to resizing `buf.data` in a different task.

Any suggestions are welcome.

**Comment by bvdmitri** [comment]
Hey!

Please do not use issue tracker for programming questions, [Julia Discourse](https://discourse.julialang.org) is a better place. You can ping [me](https://discourse.julialang.org/u/bvdmitri/summary) directly.

I can see you implementation nicely written and (probably :)) correct.

Regarding your question, to be honest I don't know about any special mechanisms in Julia to deal with high-frequency pooling in Julia. You can try to measure what time does it take to process messages and use `sleep` with dynamic `delay` argument adjusted a little bit according to the time needed to process messages.

About race conditions. Julia is a single threaded language and does not process things in parallel. Asynchronous in general **does not** mean parallel, so in principle if you use built-in async() operator or AsyncScheduler() for subjects you should not experience any race conditions. Asynchronous scheduler in Rocket.jl is built upon Julia’s `Channel` object and `@async` macro. It processes all incoming messages serially one by one and it is impossible to process two messages simultaneously with async scheduler from Rocket.jl. However as an extra measure I would agree that it might be better to guard buffer resizing with [ReentrantLock](https://docs.julialang.org/en/v1/base/parallel/#Base.ReentrantLock). It should be relatively straightforward, you will need to add `lock` and `unlock` for the buffer operations.

I will close the issue, feel free to continue this discussion on Discourse. 

And feel free to open a PR if you come up with a nice `throttlebuffer` implementation.
