### ISSUE TITLE
How to unsubsribe from a running stream

### ISSUE THREAD

**Issue by PyDataBlog** [biaslab/Rocket.jl#17]
Hi 

I am trying to use this nice package to handle some real time websocket data. How can one unsubscribe from a running stream midway? Using this example below, how can that work? From this example the stream runs and terminates at the end but how can I terminate the stream say in the middle of the stream using the `unsubscribe!` method?

```julia
using Rocket


struct MyActor <: Rocket.Actor{Int} end

Rocket.on_next!(actor::MyActor, data::Int) = println(data)
Rocket.on_error!(actor::MyActor, error)    = println(error)
Rocket.on_complete!(actor::MyActor)        = println("Completed!")

stream = from([x for x in 1:10_000])

data_stream = subscribe!(stream, MyActor())

unsubscribe!(data_stream)
```

**Comment by bvdmitri** [comment]
Hey @PyDataBlog! Thanks for your feedback! 

That is a good question. Generally speaking there are several ways to do that, but there is one pitfall so read till the end!
The easiest solution is to use a reference object (from Julia itself) for a subscription, e.g:

```julia
using Rocket

# Creates an infinite asynchronous timer observable that emits an integer every 100ms
source = timer(100, 100) 

# We create a reference for our future subscription, but it is empty for now and we cannot directly use it
subscription = Ref{Teardown}()

# `ref[] = value` syntax put some value into reference object that we can use later on
subscription[] = subscribe!(source, (d) -> begin 
    if d > 5
        # Later on we can unsubscribe on some condition
        unsubscribe!(subscription[])
        println("Unsubscribed")
    else
        # Or just do some work
        println(d)
    end
end)

```

The example above is a hand written version of 

```julia
# Here the difference though that we get an `on_complete` event at the end
subscription = subscribe!(source |> take(5), (d) -> println(d))
```

It is also possible if you use your custom `MyActor` actor, you just need to store a subscription reference inside an actor structure, e.g.:

```julia
struct MyActor <: Rocket.Actor{Int} 
    # Here we use `Base.RefValue` instead of just `Ref` because Julia returns `Base.RefValue` instance
    # we can also leave this field untyped and just use `subscription :: Any`
    subscription :: Base.RefValue{Teardown}

    MyActor() = new(Ref{Teardown}())
end

function Rocket.on_next!(actor::MyActor, data::Int) 
    if data > 5
        unsubscribe!(actor.subscription[])
        println("Unsubscribed")
    else 
        println(data)
    end
end

Rocket.on_error!(actor::MyActor, error)    = println(error)
Rocket.on_complete!(actor::MyActor)       = println("Completed!")
```

And later on we can use it as:

```julia
source = timer(100, 100)
actor   = MyActor()

actor.subscription[] = subscribe!(source, actor)
```

However, be aware that in your particular example that approach will not work by default, because `from` operator returns a synchronous stream. There is no way to `unsubscribe!` from a synchronous stream in `Rocket.jl`, its a pure Julia programming language limitation and current implementation of synchronous streams "send" all of their values all at once. But there is a way to cast any synchronous stream into asynchronous with `async()` operator. For example:

```julia
# Without async() operator unsubscription will not happen
source = from([ x^2 for x in 1:10 ]) |> async()

actor   = MyActor()

actor.subscription[] = subscribe!(source, actor);
```

```julia
# This example throws an error, because subscription reference is empty
source = from([ x^2 for x in 1:10 ])

actor   = MyActor()

actor.subscription[] = subscribe!(source, actor);
```


Some creation operators accept scheduler as their optional argument, e.g.:

```julia
source = from([ x^2 for x in 1:10 ], scheduler = AsyncScheduler())
```

`Rocket.jl` comes with a big collection of built-in operators, and it might be that you don't really need to unsubscribe manually but to use some handy operator for that, e.g. or [`take`](https://biaslab.github.io/Rocket.jl/stable/operators/filtering/take/), [`take_until`](https://biaslab.github.io/Rocket.jl/stable/operators/filtering/take_until/#operator_take_until). Some of them do work with synchronous streams as well:

```julia
# Takes 5 elements and unsubscribes or ignores values if stream is synchronous 
from(1:100) |> take(5)

# Listens for an undefined number of elements until second observable emits at least one value
timer(100, 100) |> take_until(timer(1000))
```

I hope I answered all of your question ,but don't hesitate to ask new ones!

**Comment by PyDataBlog** [comment]
@bvdmitri thanks for your swift response. In the case of websocket where I just want to stream until I get tired of seeing the stream (because I can 😄 ), what is the best approach for that scenario if I don't want to specify the condition for unsubscribing before hand?

**Comment by bvdmitri** [comment]
IMO in that case the best approach would be to use `take_until` operator, e.g.

```julia

source = create_websocket_stream()

# Here I create a subject object, read about subjects in details in documentation
notifier = Subject(Int)

subscribe!(source |> take_until(notifier), ...)

...

# Here we pass some data to out `notifier` subject that triggers our previous subscription to unsubscribe
# The actual value here does not really matter, `take_until` operator waits for any value
next!(notifier, 0)

```

You can try it with builn-in `timer` stream, like (I usually use Jupiter notebooks to test something)


```julia
# Cell 1
notifier = Subject(Int)
```

```julia
# Cell 2
subscribe!(timer(100, 100) |> take_until(notifier), logger())
```

```julia
# Cell 3 - execute when you are tired seeing all of these values :)
next!(notifier, 0)
```

**Comment by PyDataBlog** [comment]
@bvdmitri one last question before we close this issue. Let's say a scenario where I want to connect `source = create_websocket_stream()` for any time duration (say 1 hour) and save any streaming data to say a `DataFrame`. How can I persist the data in actor. In the docs, it showed how to save data in a local state in the actor (if my memory serves me right)

**Comment by bvdmitri** [comment]
@PyDataBlog As long as you have an access to `actor` object itself you can always access its local state at a later stage. I think you remember [this example](https://biaslab.github.io/Rocket.jl/stable/actors/about/#First-example). For your case you would probably need to create something like:
```
struct MyActor <: Actor{Int}
    values :: DataFrame
end
```
and later on when you saved some data you simply call `actor.values` to get your saved data.

**Comment by PyDataBlog** [comment]
Thanks so much for the walkthrough. I will be back when I get tired of staring at the stream :)

**Comment by PyDataBlog** [comment]
@bvdmitri I am back again!

How do I properly subscribe to this feed based on what we have been talking about:

```julia
using HTTP

HTTP.WebSockets.open("wss://ws.coincap.io/trades/binance") do ws
    while !eof(ws)
        println(readavailable(ws) |> JSON3.read)  # ws is the stream source and I expect as the gateway for rocket to do its thing 
    end
end


subscribe!(stream_source_above |> take_until(timer(100)), logger())
```

**Comment by bvdmitri** [comment]
For this you will need to create a custom observable type and custom subscription type as described [here](https://biaslab.github.io/Rocket.jl/stable/api/observables/) and [`here`](https://biaslab.github.io/Rocket.jl/stable/api/teardown/).

In a few words you need to create you custom Observable types and it probably will be something like: 

```

struct WebsocketObservable <: ScheduledObservable{Any}
    ... some fields ...
end

Rocket.getscheduler(::WebsocketObservable) = AsyncScheduler()

function Rocket.on_subscribe!(observable::WebsocketObservable, actor, scheduler)
     # start listening on web socket here and redirect data to actor with scheduler
     # with next!(actor, value, scheduler) to pass some data
     # with error!(actor, error, scheduler) to raise an error in an actor
     # with complete!(actor, scheduler) send a completion event
     @async begin 
        ...
     end
     return WebsocketSubscription()
end

struct WebsocketSubscription <: Teardown 
    .. some fields ...
end

Rocket.as_subscription(::Type{ <: WebsocketSubscription }) = UnsubscribableTeardownLogic()

function Rocket.on_unsubscribe(subscription::WebsocketSubscription)
    # stop listening for web socket here
    return nothing # usually unsubscription returns nothing
end

```

As another example you might take a look on [`NetworkObservable`](https://github.com/biaslab/Rocket.jl/blob/master/src/observable/network.jl) implementation.

**Comment by bvdmitri** [comment]
@PyDataBlog Can I close this issue?

**Comment by PyDataBlog** [comment]
> @PyDataBlog Can I close this issue?

Just one last query...

```julia
using Rocket, HTTP, JSON3, JSONTables, TypedTables, DataFrames, Dates


struct WebsocketObservable <: Subscribable{Any}
    # Any field here
end

struct MyActor <: Rocket.Actor{Any} end

Rocket.getscheduler(::WebsocketObservable) = AsyncScheduler()

function Rocket.on_subscribe!(observable::WebsocketObservable, actor)
    @async begin
        try
            HTTP.WebSockets.open("wss://ws.coincap.io/trades/binance") do ws
                while isopen(ws)
                    if !eof(ws)
                        next!(actor, readavailable(ws) |> JSON3.read)
                    else
                        complete!(actor)
                    end
                end
            end
        catch e
            if !e.is_a(EOFError)
                error!(actor, e)
            end
        end
    end
    return WebsocketSubscription()
end


struct WebsocketSubscription <: Teardown
    #.. some fields ...
end

Rocket.as_teardown(::Type{ <: WebsocketSubscription }) = UnsubscribableTeardownLogic()

function Rocket.on_unsubscribe!(subscription::WebsocketSubscription)
    # stop listening for web socket here
    return nothing # usually unsubscription returns nothing
end

# testing custom Actor
Rocket.on_next!(actor::MyActor, data::Any) = println(data)  # do something with json data
Rocket.on_error!(actor::MyActor, error)    = println(error)
Rocket.on_complete!(actor::MyActor)        = println("Done Watching Stream!")


struct StoreActor <: Rocket.Actor{Any}
    values :: AbstractDataFrame
    StoreActor() = new(DataFrame())
end

# save some data in the local state
Rocket.on_next!(actor::StoreActor, data::Any)   = append!(actor.values, data |> DataFrame, cols=:union)
Rocket.on_error!(actor::StoreActor, error)      = println(error)
Rocket.on_complete!(actor::StoreActor)          = println("Completed: $(actor.values |> length) rows added")

df_actor = StoreActor()

subscribe!(WebsocketObservable() |> take_until(timer(1_000)), MyActor())  # warm up

subscribe!(WebsocketObservable() |> take_until(timer(20_000)), df_actor)

```

The REPL seem to hang after some few runs or when idle after running some few subscription runs. Dunno if this is Rocket related or Julia related tho

**Comment by bvdmitri** [comment]
First of all if you want to process values asynchronously its better to use `ScheduledSubscribable` abstract type (as in my example) and pass extra `scheduler` argument to `on_subscribe!` function (and also pass it to `next!(actor, value, scheduler)` and `complete!(actor, scheduler)`). 

```julia
struct WebSocketObservable <: ScheduledSubscribable{Any} end

Rocket.getscheduler(::WebSocketObservable) = AsyncScheduler()

function Rocket.on_subscribe!(source::WebSocketObservable, actor, scheduler)
    @async begin
        ...
        next!(actor, value, scheduler)
        ...
        complete!(actor, scheduler)
        ...
    end
    return WebSocketSubscription()
end
```

Second, it seems to be that your `on_unsubscribe!` function is empty, but you need to implement unsubscription logic and stop listening for websocket eventually, without this you code can easily hang after a few runs because you never close existing web sockets connections.

```julia
function Rocket.on_unsubscribe!(subscription::WebsocketSubscription)
    # stop listening for web socket here
    return nothing # usually unsubscription returns nothing
end
```

Rocket does not unsubscribe for you and doesn't know how to close web socket channel, for this example to work you need to implement this logic in `on_unsubscribe!` function. You also need to call `unsubscribe!` function later on manually when you don't need values from your websocket (you also may need to close web socket connection after completion event).

**Comment by PyDataBlog** [comment]
@bvdmitri I am back again with some questions. I am trying to subscribe to a WebSocket protocol for realtime data from [polygon.io ](https://polygon.io/docs/websockets/getting-started)

Here's my attempt (not working) so far given what you told me earlier: 
```julia
using Rocket
using HTTP
using JSON3


struct WebSocketObservable <: ScheduledSubscribable{Any}
    # Any field here
    api_key::AbstractString
    tickers::AbstractString
end


struct WebsocketSubscription <: Teardown
    #.. some fields ...
    live_socket::Any
    tickers::AbstractString
end


struct MyActor <: Rocket.Actor{Any} end

Rocket.getscheduler(::WebSocketObservable) = AsyncScheduler()


function Rocket.on_subscribe!(source::WebSocketObservable, actor, scheduler)

    @async begin
        try
            HTTP.WebSockets.open("wss://socket.polygon.io/crypto") do ws
                while isopen(ws)
                    # Authenticate & Subscribe to ticker stream
                    write(ws, JSON3.read("""{"action":"auth", "params":$(source.api_key)}"""))
                    write(ws, JSON3.read("""{"action":"subscribe", "params":$(source.tickers)}"""))

                    if !eof(ws)
                        next!(actor, readavailable(ws) |> JSON3.read, scheduler)
                    else
                        complete!(actor, scheduler)
                    end
                end
            end
        catch e
            if !e.is_a(EOFError)
                error!(actor, e, scheduler)
            end
        end
    #return WebsocketSubscription(ws, source.tickers)
    end

    return WebsocketSubscription(ws, source.tickers)  # can't get access to ws in the above
end


function Rocket.on_unsubscribe!(subscription::WebsocketSubscription)
    # stop listening for web socket here
    write(subscription.live_socket, JSON3.read("""{"action":"unsubscribe", "params":$(subscription.tickers)}"""))

    # usually unsubscription returns nothing
    return nothing
end


# testing custom Actor
Rocket.on_next!(actor::MyActor, data::Any) = println(data)
Rocket.on_error!(actor::MyActor, error)    = println(error)
Rocket.on_complete!(actor::MyActor)        = println("Done Watching Stream!")


obsv = WebSocketObservable("API_KEY", "XT.*")
subscription = subscribe!(obsv, logger())
unsubscribe!(subscription)

```

First, question is that, how can I return `ws` outside of the `do` statement? 
Secondly, is this design concept a valid one in general?

**Comment by bvdmitri** [comment]
@PyDataBlog Please don't use issue tracker for programming questions. You can use [Julia Discourse](https://discourse.julialang.org) for those types of questions so more people can see and answer your questions. Returning `ws` from is not related to Rocket library but to Julia and WebSockets library. Unfortunately I am not familiar with WebSockets library and cannot help you with that issue.

You can also use reference object `Ref` to return something from an `@async` block:

```julia

function Rocket.on_subscribe!(source::WebSocketObservable, actor, scheduler)
    ws = Ref{Any}(nothing)
    @async begin
            ...
            ws[] = open_websocket_connection_here()
            ...
    end
    return WebsocketSubscription(ws, source.tickers)  # can't get access to ws in the above
end
```

or you can create `ws` object right before an `@async` block (as in `NetworkObservable`):

```julia
function Rocket.on_subscribe!(source::WebSocketObservable, actor, scheduler)
    ws = open_websocket_connection_here()
    @async begin
            ...
            read(ws, ...)
            ...
    end
    return WebsocketSubscription(ws, source.tickers)  # can't get access to ws in the above
end
```

I will close this ticket since there is no issue with `Rocket.jl` and the original issue has been resolved as well.
