### ISSUE TITLE
Usability in REPL

### ISSUE THREAD

**Issue by hdlopeza** [biaslab/Rocket.jl#21]
Hi, great work!!!, congratulations.
I am new with Julia and reactx, i was tried to use Rocket in REPL console, but I don know how to syncronize "a" variable, subscribe it and then show the change whe I want change the new value of "a", I am trying with schedule, task an nothing.  PleasePlease can you show how to useit?, thanks a lot

**Comment by bvdmitri** [comment]
Please do not use the issue tracker for questions, you can ask questions on [Discourse](https://discourse.julialang.org).

Also I suggest you to check our [documentation](https://biaslab.github.io/Rocket.jl/stable/) first.
