### ISSUE TITLE
How to send messages between actors

### ISSUE THREAD

**Issue by bicepjai** [biaslab/Rocket.jl#7]
When we have multiple actors in the system, how do we send messages between the actors ?

**Comment by bvdmitri** [comment]
There is no principled limitation for sending messages between actors. You can use `next!(actor, data)` function if you want to manually send some message to an actor. Another option would be to use shared `Subject` object for messages multicasting between multiple actors.

For more info see [docs](https://biaslab.github.io/Rocket.jl/stable/).
