### ISSUE TITLE
Error in map operator in documentation

### ISSUE THREAD

**Issue by griera95** [biaslab/Rocket.jl#8]
Hi,

There is a bug in some code in the documentation, where two type parameters are passed to the map operator instead of one. It is kind of silly, but I figured I should notify so that no misunderstandings arrise for new users.

![rocket-error](https://user-images.githubusercontent.com/30684112/100228560-253c4600-2f23-11eb-8643-0390bb633c57.png)

**Comment by griera95** [comment]
Also, in the next example, I think that `next(Int)` should be `next()` instead.

**Comment by griera95** [comment]
Also, in the next example, I think that `first(Int)` should be `first()` instead.

**Comment by bvdmitri** [comment]
Dear @griera95,

Good catch! Thank you, I'll update this section in the documentation. Actual update will happen after automatic TravisCI build and which can take sometime.

**Comment by bvdmitri** [comment]
@griera95 I made a fix for this section. There also was an old note about bad performance of lambda-based operators which is no longer true.
